version: "3"
services:
  app:
    image: node:14.16.0-alpine
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    working_dir: /app
    command: /bin/sh -c "npm install && npm test && npm start"


